apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      volumes:
        - name: shared-dir
          emptyDir: {}
        # - name: ping-count
        #   persistentVolumeClaim:
        #     claimName: ping-count
      containers:
      - name: log-output
        image: log-output
        imagePullPolicy: Never
        volumeMounts:
          - name: shared-dir
            mountPath: /var/shared
          # - name: ping-count
          #   mountPath: /var/ping-count
      - name: timestamper
        image: log-output-timestamper
        imagePullPolicy: Never
        volumeMounts:
          - name: shared-dir
            mountPath: /var/shared
