apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output
  namespace: exercise-apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      volumes:
        - name: shared-dir
          emptyDir: {}
        # - name: ping-count
        #   persistentVolumeClaim:
        #     claimName: ping-count
        - name: config
          configMap:
            name: log-output-config
            items:
              - key: information.txt
                path: information.txt
      containers:
      - name: log-output
        image: europe-north1-docker.pkg.dev/benjami-lab/exercise-apps/log-output
        imagePullPolicy: Always
        volumeMounts:
          - name: shared-dir
            mountPath: /var/shared
          # - name: ping-count
          #   mountPath: /var/ping-count
          - name: config
            mountPath: /var/config
        env:
          - name: MESSAGE
            valueFrom:
              configMapKeyRef:
                name: log-output-config
                key: MESSAGE
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 5
          httpGet:
            path: /health
            port: 8080
      - name: timestamper
        image: europe-north1-docker.pkg.dev/benjami-lab/exercise-apps/log-output-timestamper
        imagePullPolicy: Always
        volumeMounts:
          - name: shared-dir
            mountPath: /var/shared
