# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: log-output
#   namespace: exercise-apps
# spec:
#   rules:
#   - http:
#       paths:
#       - path: /
#         pathType: Prefix
#         backend:
#           service:
#             name: log-output
#             port:
#               number: 2345