apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-pong
  namespace: exercise-apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-pong
  template:
    metadata:
      labels:
        app: ping-pong
    spec:
      # volumes:
      #   - name: ping-count
      #     persistentVolumeClaim:
      #       claimName: ping-count
      containers:
      - name: ping-pong
        image: europe-north1-docker.pkg.dev/benjami-lab/exercise-apps/ping-pong
        imagePullPolicy: Always
        # volumeMounts:
        #   - name: ping-count
        #     mountPath: /var/ping-count
        env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pingpong-db-credentials
              key: password
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 5
          httpGet:
            path: /health
            port: 8080
