# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: ping-pong
#   namespace: exercise-apps
# spec:
#   rules:
#   - http:
#       paths:
#       - path: /pingpong
#         pathType: Prefix
#         backend:
#           service:
#             name: ping-pong
#             port:
#               number: 1234