apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ping-count
  namespace: exercise-apps
spec:
  storageClassName: tmp-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi