apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
  namespace: todo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      volumes:
        - name: todo-cache
          persistentVolumeClaim:
            claimName: todo-cache
      containers:
      - name: todo-app
        image: localhost/todo-app
        imagePullPolicy: Never
        volumeMounts:
          - name: todo-cache
            mountPath: /var/cache
      - name: todo-backend
        image: localhost/todo-backend
        imagePullPolicy: Never
        env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: todo-db-credentials
              key: password
