apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: todo-app
  namespace: $NAMESPACE
spec:
  replicas: 4
  selector:
    matchLabels:
      app: todo-app
  strategy:
    canary:
      steps:
      - setWeight: 25
      - pause:
          duration: 30s
      - setWeight: 50
      - analysis:
          templates:
          - templateName: cpu-usage
      - pause:
          duration: 30s
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      volumes:
        - name: todo-cache
          emptyDir: {} # Each pod has its own cache, and it is ephemeral
          # Not ideal, but I don't really want to spin an NFS server (even if it is managed by GCP...)
      containers:
      - name: todo-app
        image: $IMAGE_REPO/todo-app:$IMAGE_TAG
        imagePullPolicy: Always
        volumeMounts:
          - name: todo-cache
            mountPath: /var/cache
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 5
          httpGet:
            path: /health
            port: 8080
        livenessProbe:
          initialDelaySeconds: 20
          periodSeconds: 5
          httpGet:
            path: /health
            port: 8080
      - name: todo-backend
        image: $IMAGE_REPO/todo-backend:$IMAGE_TAG
        imagePullPolicy: Always
        env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: todo-db-credentials
              key: password
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 5
          httpGet:
            path: /health
            port: 8081
        livenessProbe:
          initialDelaySeconds: 20
          periodSeconds: 5
          httpGet:
            path: /health
            port: 8081
