apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
  namespace: $NAMESPACE
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  strategy:
    type: Recreate # We have RWO volume, this is simplest to "fix" it
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      volumes:
        - name: todo-cache
          persistentVolumeClaim:
            claimName: todo-cache
      containers:
      - name: todo-app
        image: $IMAGE_REPO/todo-app:$IMAGE_TAG
        imagePullPolicy: Always
        volumeMounts:
          - name: todo-cache
            mountPath: /var/cache
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 5
          httpGet:
            path: /health
            port: 8080
        livenessProbe:
          initialDelaySeconds: 20
          periodSeconds: 5
          httpGet:
            path: /health
            port: 8080
      - name: todo-backend
        image: $IMAGE_REPO/todo-backend:$IMAGE_TAG
        imagePullPolicy: Always
        env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: todo-db-credentials
              key: password
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 5
          httpGet:
            path: /health
            port: 8081
        livenessProbe:
          initialDelaySeconds: 20
          periodSeconds: 5
          httpGet:
            path: /health
            port: 8081
