apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: todo-cache
  namespace: todo-app
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi